name: "Build Docker Image"
description: "Build Docker image for a single platform and push by digest"
author: "thpham"

inputs:
  registry:
    description: "Container registry (e.g., ghcr.io)"
    required: true
  image-name:
    description: "Full image name without tag"
    required: true
  platform:
    description: "Target platform (e.g., linux/amd64)"
    required: true
  context:
    description: "Docker build context path"
    required: false
    default: "."
  dockerfile:
    description: "Dockerfile path relative to context"
    required: false
    default: "Dockerfile"
  build-args:
    description: "Docker build arguments (newline-separated KEY=VALUE pairs)"
    required: false
    default: ""
  version:
    description: "Version tag for image"
    required: true
  cache-scope:
    description: "Buildx cache scope identifier"
    required: false
    default: ""
  artifact-name:
    description: "Name of build artifacts to download"
    required: false
    default: ""
  artifact-destination:
    description: "Destination directory for artifacts in Docker context"
    required: false
    default: ""
  digest-artifact-prefix:
    description: "Prefix for digest artifact name (e.g., 'digests' or 'release-digests')"
    required: false
    default: "digests"
  artifact-retention-days:
    description: "Retention days for uploaded digest artifact"
    required: false
    default: "1"
  registry-username:
    description: "Registry username for authentication"
    required: false
    default: ""
  registry-password:
    description: "Registry password/token for authentication"
    required: true

outputs:
  digest:
    description: "Image digest (sha256:...)"
    value: ${{ steps.build.outputs.digest }}
  platform-pair:
    description: "Normalized platform name (e.g., linux-amd64)"
    value: ${{ steps.prepare.outputs.platform_pair }}

runs:
  using: "composite"
  steps:
    - name: Prepare platform pair
      id: prepare
      shell: bash
      run: |
        platform="${{ inputs.platform }}"
        PLATFORM_PAIR="${platform//\//-}"
        echo "platform_pair=${PLATFORM_PAIR}" >> "$GITHUB_OUTPUT"
        echo "PLATFORM_PAIR=${PLATFORM_PAIR}" >> "$GITHUB_ENV"

    - name: Download Build Artifacts
      if: inputs.artifact-name != ''
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v4
      with:
        name: ${{ inputs.artifact-name }}
        path: /tmp/build-artifacts

    - name: Flatten Artifacts to Docker Context
      if: inputs.artifact-name != '' && inputs.artifact-destination != ''
      shell: bash
      env:
        BUILD_CONTEXT: ${{ inputs.context }}
        ARTIFACT_DEST: ${{ inputs.artifact-destination }}
      run: |
        DEST_DIR="${BUILD_CONTEXT}/${ARTIFACT_DEST}"
        mkdir -p "${DEST_DIR}"
        echo "=== Downloaded artifacts ==="
        find /tmp/build-artifacts -type f
        echo "=== Flattening to ${DEST_DIR}/ ==="
        find /tmp/build-artifacts -type f -exec cp {} "${DEST_DIR}/" \;
        echo "=== Flattened artifacts ==="
        ls -la "${DEST_DIR}/"

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

    - name: Login to Container Registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-username != '' && inputs.registry-username || github.actor }}
        password: ${{ inputs.registry-password }}

    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}

    - name: Build and Push by Digest
      id: build
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      env:
        BUILD_CONTEXT: ${{ inputs.context }}
        BUILD_DOCKERFILE: ${{ inputs.dockerfile }}
      with:
        # zizmor: ignore[template-injection] - workflow_call input from trusted callers, path value only
        context: ${{ env.BUILD_CONTEXT }}
        file: ${{ env.BUILD_CONTEXT }}/${{ env.BUILD_DOCKERFILE }}
        platforms: ${{ inputs.platform }}
        build-args: |
          VERSION=${{ inputs.version }}
          ${{ inputs.build-args }}
        labels: ${{ steps.meta.outputs.labels }}
        outputs: type=image,name=${{ inputs.registry }}/${{ inputs.image-name }},push-by-digest=true,name-canonical=true,push=true
        cache-from: type=gha,scope=${{ inputs.cache-scope != '' && inputs.cache-scope || format('{0}-{1}', github.repository, inputs.platform) }}
        cache-to: type=gha,scope=${{ inputs.cache-scope != '' && inputs.cache-scope || format('{0}-{1}', github.repository, inputs.platform) }},mode=max

    - name: Export Digest
      shell: bash
      env:
        DIGEST: ${{ steps.build.outputs.digest }}
      run: |
        mkdir -p /tmp/digests
        touch "/tmp/digests/${DIGEST#sha256:}"

    - name: Upload Digest
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: ${{ inputs.digest-artifact-prefix }}-${{ env.PLATFORM_PAIR }}
        path: /tmp/digests/*
        if-no-files-found: error
        retention-days: ${{ inputs.artifact-retention-days }}
